[package]
name = "neveko_market"
version = "0.4.4-alpha"
edition = "2021"
publish = false

[dependencies]
chrono = "0.4.23"
env_logger = "0.10.0"
neveko_core = { path = "../neveko-core" }
log = "0.4"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
